### ISSUE TITLE
Firebase Register Lesson 02_02e is out of date

### ISSUE THREAD

**Issue by danmv** [planetoftheweb/angularregistration#3]
Hi there, 

I am following this tutorial but I am not able to move forward because it is using the Firebase Legacy API. 
I tried troubleshooting but was not able to. When would this be update to reflect the new way to initialize firebase and use the auth method?

**Comment by salmanpatnee** [comment]
Follow this link [angularfire](https://github.com/firebase/angularfire) its a new version of library and complete API reference I was also watching ray course and stuck at some point e.g Ray used createUser for registration of users but its no longer working according to Documentation and new API i used $createUserWithEmailAndPassword(email, password). this way i have completed the course and also project and i ended up with very different code and methods.

**Comment by pavanchokshi** [comment]
Hi Ray,

I was following this tutorial on LinkedIn learning, but I found that the Firebase used in the tutorial is outdated. Is it possible for you to update this tutorial with latest Firebase API ?

**Comment by planetoftheweb** [comment]
I'm recording the update now. In the meantime, you can look at a branch called newtarget for the changes that will work with the new API. I'm also going to clone the master branch into one called oldmaster so that you can run a comparison. I will rename the 02_XX branches 02_XXX_o and remove those since I'll be re-recording.
