### ISSUE TITLE
Retriving Data form Firebase real time database: node key??

### ISSUE THREAD

**Issue by salmanpatnee** [planetoftheweb/angularregistration#4]
I am successfully storing data in firebase real time database but can't figure out how to retrieve it from DB 
i using this URL to sroring data `firebase.database().ref().child("users/" + regUser.uid);` but it is stroting thje data in this mannaer here is the snapshot of my database https://www.dropbox.com/s/8l6jfdqmjcx879l/Screenshot%202016-09-20%2023.12.02.png?dl=0
The structure is angularreg-40c6b->users->uid->"Unknown key"
The whole data is under that "Unknow key"

How to retrive??

**Comment by planetoftheweb** [comment]
The new way to do things is through child.

I'm recording the update now. In the meantime, you can look at a branch called newtarget for the changes that will work with the new API. I'm also going to clone the master branch into one called oldmaster so that you can run a comparison. I will rename the 02_XX branches 02_XXX_o and remove those since I'll be re-recording.
